version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Specify your desired Python version
    commands:
      - echo "Installing dependencies..."
      - pip install -r src/lambda-functions/requirements.txt

  pre_build:
    commands:
      - echo "Running unit tests..."
      # - pytest tests/unit

  build:
    commands:
      - echo "Packaging Lambda functions..."
      # - cd src/lambda-functions/function1/
      # - zip -r9 ../../build/function1.zip .
      # - cd ../function2/
      # - zip -r9 ../../build/function2.zip .
      # - cd ../function3/
      # - zip -r9 ../../build/function3.zip .

artifacts:
  files:
    - build/*.zip
