AWSTemplateFormatVersion: '2010-09-09'
Description: RDS setup inside a VPC and storing connection credentials in Secrets Manager
Resources:
  # CognitoStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: 's3://your-template-bucket-path/cognito.yaml'

  # ApiStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: 's3://your-template-bucket-path/api.yaml'

  # S3Stack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: 's3://your-template-bucket-path/s3.yaml'

  SnsSqsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://aws-dev-poc-bucket-stockholm.s3.eu-north-1.amazonaws.com/aws-associate-dev-poc/cfn-templates/services/sns-sqs.yaml

  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://aws-dev-poc-bucket-stockholm.s3.eu-north-1.amazonaws.com/aws-associate-dev-poc/cfn-templates/services/dynamodb.yaml

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://aws-dev-poc-bucket-stockholm.s3.eu-north-1.amazonaws.com/aws-associate-dev-poc/cfn-templates/services/rds.yaml