AWSTemplateFormatVersion: '2010-09-09'
Description: RDS setup inside a VPC and storing connection credentials in Secrets Manager

Resources:

  CognitoUserDBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: CognitoUserDBConnection
      Description: Connection credentials for the Cognito user details RDS instance
      GenerateSecretString:
        SecretStringTemplate: '{"username": "hardcoded_username", "password": "hardcoded_password"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/'

  CognitoUserDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: '20'
      DBInstanceClass: 'db.t2.micro'
      Engine: 'mysql'
      MasterUsername: !Sub '{{resolve:secretsmanager:${CognitoUserDBSecret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${CognitoUserDBSecret}:SecretString:password}}'
      DBName: 'CognitoUsers'
      MultiAZ: false
      BackupRetentionPeriod: '3'
      VPCSecurityGroups:
        - Ref: DBSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup

  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnet group for CognitoUserDB
      SubnetIds:
        - subnet-019fd83847dcd8cb2  # Replace with your subnet IDs
        - subnet-081a0a52854c4f7be

  DBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow MySQL connections
      VpcId: vpc-0938e11b961748f12 # Replace with your VPC ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          CidrIp: 0.0.0.0/0  # You might want to restrict this to your Lambda's security group or specific IPs
