AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for storing uploaded files and lifecycle configuration

Parameters:
  SNSName:
    Description: "Name for the SNS Topic"
    Type: String
    Default: "MySNSTopic"

  SQSName:
    Description: "Name for the SQS Queue"
    Type: String
    Default: "PoCSQS"

Resources:
  UploadedFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aws-dev-poc-bucket-stockholm-134  # Make sure to provide a unique name
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:*
            Topic: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${SNSName}
      LifecycleConfiguration:
        Rules:
          - Id: MoveToInfrequentAccess
            Status: Enabled
            Transitions:
              - TransitionInDays: 1
                StorageClass: INTELLIGENT_TIERING

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Sub https://sqs:${AWS::Region}.amazonaws.com/${AWS::AccountId}/${SQSName}
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: sqs:SendMessage
            Resource: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${SQSName}

Outputs:
  BucketName:
    Description: "S3 Bucket Name"
    Value: !Ref UploadedFilesBucket
  BucketARN:
    Description: "Bucket ARN"
    Value: !GetAtt UploadedFilesBucket.Arn
