AWSTemplateFormatVersion: '2010-09-09'
Description: Amazon SNS topic with Amazon SQS Subscription

Resources:

  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "MySNSTopic"
      TopicName: "MySNSTopic"

  MySQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 'PoCSQS'
    

  MyTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref MySNSTopic
      Endpoint: !GetAtt MySQSQueue.Arn

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MySQSQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: sqs:SendMessage
            Resource: !GetAtt MySQSQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref MySNSTopic
